import Head from 'next/head'
import dynamic from "next/dynamic"

const Footer = dynamic(() => import('./Footer'))
const Navbar = dynamic(() => import('./Navbar'))

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>PokeNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Navbar />
      <main className='main-container'>
        {children}
      </main>
      <Footer />
    </>
  )
}

export default Layout